// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVr1PpkACMTm3hrREMXCMsm7ZjcV2mJiw',
    appId: '1:310288585268:web:465d8b62ab50f8b9013061',
    messagingSenderId: '310288585268',
    projectId: 'mailler-d87d5',
    authDomain: 'mailler-d87d5.firebaseapp.com',
    storageBucket: 'mailler-d87d5.firebasestorage.app',
    measurementId: 'G-6DD25QKL2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3rZ4Wy0I8JPjWmVUzxLVt2XbJR91uZ_4',
    appId: '1:310288585268:android:6b0d1fe8eda4a3a6013061',
    messagingSenderId: '310288585268',
    projectId: 'mailler-d87d5',
    storageBucket: 'mailler-d87d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgpYAsZv5YAyIQfkbkgOls_223sniuOAI',
    appId: '1:310288585268:ios:55db2c6464349ea0013061',
    messagingSenderId: '310288585268',
    projectId: 'mailler-d87d5',
    storageBucket: 'mailler-d87d5.firebasestorage.app',
    iosBundleId: 'com.example.emailsSender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgpYAsZv5YAyIQfkbkgOls_223sniuOAI',
    appId: '1:310288585268:ios:55db2c6464349ea0013061',
    messagingSenderId: '310288585268',
    projectId: 'mailler-d87d5',
    storageBucket: 'mailler-d87d5.firebasestorage.app',
    iosBundleId: 'com.example.emailsSender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVr1PpkACMTm3hrREMXCMsm7ZjcV2mJiw',
    appId: '1:310288585268:web:6661703025e5ccb5013061',
    messagingSenderId: '310288585268',
    projectId: 'mailler-d87d5',
    authDomain: 'mailler-d87d5.firebaseapp.com',
    storageBucket: 'mailler-d87d5.firebasestorage.app',
    measurementId: 'G-J8R4Y8NQ5M',
  );
}
